spring:
  application:
    name: capability

  r2dbc:
    url: r2dbc:postgresql://localhost:5433/capability
    username: postgres
    password: 1234

  flyway:
    enabled: true
    locations: classpath:db/migration
    url: jdbc:postgresql://localhost:5433/capability
    user: postgres
    password: 1234

server:
  port: 8081

springdoc:
  swagger-ui:
    path: "/api/doc/capability/swagger-ui.html"
  api-docs:
    path: "/api/doc/capability/api-docs"

routes:
  paths:
    capabilities: "/api/v1/capabilities"
    capabilities-list: "/api/v1/capabilities/list"
    associate-capabilities: "/api/v1/capabilities/bootcamp-associations"
    capabilities-by-bootcamp-id: "/api/v1/capability/botcamps/{bootcampId}/capabilities"
    delete-bootcamp-cascade: "/api/v1/capability/bootcamps/{bootcampId}"



adapter:
  clients:
    timeout: 5000
    clients:
      tech:
        base-url: "http://localhost:8080/api/v1"