CREATE TABLE IF NOT EXISTS bootcamp_capability (
	bootcamp_capability_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	bootcamp_id BIGINT NOT NULL,
	capability_id BIGINT NOT NULL,
	CONSTRAINT uq_bootcamp_capability UNIQUE (bootcamp_id, capability_id),
	CONSTRAINT fk_bootcamp_capability_capability
		FOREIGN KEY (capability_id) REFERENCES capability(id)
);

CREATE INDEX IF NOT EXISTS idx_bootcamp_capability_capability_id
	ON bootcamp_capability (capability_id);


